name: Chromatic

on:
  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
  # Path filters are not evaluated for pushes to tags.
  pull_request:
    paths:
      - packages/core/package.json
      - packages/core/src/**
  push:
    paths:
      - packages/core/package.json
      - packages/core/src/**

jobs:
  chromatic-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
